/**
 * Every economic constant lives here.
 *
 * Shape taken from the idle/tycoon genre rather than picked by hand: production grows
 * ~x6.6 per tier while cost grows ~x13, so the cost-per-income ratio DOUBLES at each
 * step. A flat ratio makes all tiers equivalent and turns every absolute price trivial
 * two tiers later. Prestige uses a cube root of lifetime earnings, so returns diminish
 * by construction.
 */
export const PRODUCTION_PER_RARITY = [1, 7, 44, 287, 1897, 12523, 82654] as const

/**
 * Derived: expected output x target payback, where payback doubles per tier.
 *
 * Rederived from the tables themselves on 25 Aug, because the previous figures did not do
 * what this comment says. Measured against `CRATE_WEIGHTS` and `MUTATIONS`, a Basic crate
 * paid for itself in ten seconds against a stated sixty, and every price was between 2.4 and
 * 5.9 times too low. The factor that had gone missing is the mutation multiplier: a third of
 * items carry one, worth x1.4921 on average, and the old derivation priced the crate as if
 * none did.
 *
 * The distortion also shrank with tier, 5.9 down to 2.4, which flattened the curve this file
 * exists to create: the early game was a firehose and the late game was not. Second-by-second
 * simulation of the old numbers had six slots full in twenty-four seconds, before a new
 * player can read what a crate is.
 *
 * The scale is the genre's, and deliberately not the event's.
 *
 * There was a version of this file tuned so a three-minute visitor would reach the upper
 * floors. That is the wrong thing to optimise: it buys a demo by flattening the game into
 * something finished in half an hour. What a short visit has to show is the LOOP, not the
 * ladder. Simulated at these prices, a first-time player buys their first crate at one
 * minute and has all six slots full at 2.3, so three minutes shows the whole cycle five
 * times over, and theft is available from the first second because it is gated by nothing.
 * The ladder stays where it belongs: second floor at 24 minutes, third at 1.3 hours.
 */
export const CRATE_PRICE = [2018, 17425, 165140, 1473212] as const

export const CRATE_PAYBACK_S = [60, 120, 240, 480] as const

/**
 * A floor returns in 2.5 crate-paybacks: it is the safe purchase, and it is capped at three.
 *
 * Both a floor and a prestige roughly double income at their first step, so if one is much
 * cheaper the other never gets chosen and the decision the loop is built on does not exist.
 * The floor stays the cheaper of the two, which is paid for by the cap; prestige has none.
 * Six slots at three hundred seconds each.
 */
export const FLOOR_PRICES = [0, 261371, 1238549] as const

/**
 * Prestige 1 lands at about thirty-one minutes of real play, simulated rather than assumed.
 *
 * Every earlier value here was calibrated against a guess at the player's income: 75 000
 * against an assumed 42/s, then 430 000 against a measured 288/s but with the crate prices
 * that turned out to be six times too low. The number is now the outcome of a second-by-
 * second run of the whole loop under the prices above, swept across candidates and read off
 * the milestones it produces.
 *
 * Cost grows with the cube of the tier, so the ladder is long by construction: the first
 * prestige at 2.4 hours, the sixth at 106, the twelfth past four hundred. That is the point.
 * A tycoon is a thing somebody can still be playing in three months, and a threshold picked
 * so a visitor reaches the top of it in an afternoon would have thrown that away.
 */
export const PRESTIGE_THRESHOLD = 2_500_000

export function prestigeFor(cumul: number): number {
  return cumul <= 0 ? 0 : Math.floor(Math.cbrt(cumul / PRESTIGE_THRESHOLD))
}

export function lifetimeForPrestige(n: number): number {
  return n <= 0 ? 0 : Math.round(n * n * n * PRESTIGE_THRESHOLD)
}

export function prestigeMultiplier(n: number): number {
  return 1 + Math.max(0, n)
}

/**
 * High enough that nobody meets it.
 *
 * Twelve was a real ceiling: reachable, and then nothing beyond. The tiers are generated by
 * a formula, so having more of them costs nothing at all, and a progression that ends is a
 * progression a long-term player eventually falls off. At the cube scaling above, tier
 * thirty asks for sixty-seven billion.
 */
export const MAX_PRESTIGE = 30

/**
 * Offline earnings are capped in SECONDS OF PRODUCTION, not in hours. An hour-based cap
 * pays an amount that grows with production, so it skips more and more content as the
 * player advances; a production-based cap always grants the same head start.
 */
export const OFFLINE_RATE_V2 = 0.35
export const OFFLINE_CAP_PRODUCTION_S = 900
