/**
 * Generated by tools/ui/build-font-atlas.py. Do not edit by hand.
 *
 * Baloo 2 ExtraBold, SIL Open Font License 1.1. Advances are a fraction of one cell, which
 * is what keeps a string proportional instead of typewritten.
 */
export const ATLAS = { cols: 8, rows: 8, glyphs: '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ.,:+-/%x$!?() ' } as const

export const ADVANCE: Record<string, number> = {
  "0": 0.5018,
  "1": 0.3254,
  "2": 0.4323,
  "3": 0.4290,
  "4": 0.4985,
  "5": 0.4323,
  "6": 0.4620,
  "7": 0.3992,
  "8": 0.4637,
  "9": 0.4620,
  "A": 0.5193,
  "B": 0.5126,
  "C": 0.4729,
  "D": 0.5515,
  "E": 0.4539,
  "F": 0.4397,
  "G": 0.5499,
  "H": 0.5565,
  "I": 0.2526,
  "J": 0.3412,
  "K": 0.5093,
  "L": 0.4248,
  "M": 0.6600,
  "N": 0.5623,
  "O": 0.5822,
  "P": 0.4812,
  "Q": 0.5839,
  "R": 0.5043,
  "S": 0.4563,
  "T": 0.4604,
  "U": 0.5499,
  "V": 0.5250,
  "W": 0.7147,
  "X": 0.4977,
  "Y": 0.4753,
  "Z": 0.4637,
  ".": 0.1971,
  ",": 0.2013,
  ":": 0.2136,
  "+": 0.4513,
  "-": 0.2932,
  "/": 0.2841,
  "%": 0.6616,
  "x": 0.4331,
  "$": 0.4679,
  "!": 0.2468,
  "?": 0.4124,
  "(": 0.2526,
  ")": 0.2526,
  " ": 0.1656
}

/**
 * Which file carries which colour, named after a hash of its own pixels.
 *
 * The tint that would let one white atlas serve every colour is not applied on the mobile
 * client, so the colour lives in the file. And a file whose name never changes is a file a
 * cache will happily keep serving after its contents have: a gold counter stayed gold on a
 * handset for a build and a half after it had been rewritten green. The hash makes that
 * impossible.
 */
export const FONT_FILES = {
  money: 'font-money-699999f5.png',
  bonus: 'font-bonus-5e35e752.png',
  name: 'font-name-0cfc5bfa.png',
  danger: 'font-danger-feaa6a1e.png',
  ink: 'font-ink-fb965172.png',
  shadow: 'font-shadow-5ed5bcad.png'
} as const
